spring:
  application:
    name: manage-machine-information
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
    driverClassName: org.postgresql.Driver
    hikari:
      poolSize: 10
      connectionTimeout: 5000
      maxLifetime: 300000
      idleTimeout: 60000
      leakDetectionThreshold: 30000
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
server:
  port : 8080
